### ISSUE TITLE
RISC V support?

### ISSUE THREAD

**Issue by Kakadu** [nix-ocaml/nix-overlays#1026]
Does this task going to be complicated? 
Any chance that newcomer like me could manage doing this by textually replacing  arm by riscv?

**Comment by anmonteiro** [comment]
In theory it should be as easy as adding a line like the following, but for `pkgsCross.riscv64` instead:

https://github.com/nix-ocaml/nix-overlays/blob/9d44308f7703b483711735e6004d1be201ed5eab/overlay/default.nix#L53-L54

**Comment by anmonteiro** [comment]
Seems to work. I tried locally with doi2bib:

```shell
$ nix run nixpkgs#file -- ./result/bin/doi2bib
./result/bin/doi2bib: ELF 64-bit LSB executable, UCB RISC-V, RVC, double-float ABI, version 1 (SYSV), dynamically linked, interpreter /nix/store/fx1zc87vxzmfm3yk4x4wwmwg21xnc6pn-glibc-riscv64-unknown-linux-gnu-2.37-8/lib/ld-linux-riscv64-lp64d.so.1, for GNU/Linux 4.15.0, not stripped
```

**Comment by Kakadu** [comment]
How did you tested it? I added a few lines to flake.nix inside nat2bit but got a compilation issue about `stdup` while building a compiler...

https://gist.github.com/Kakadu/942b309e1910ef332b3e44ba95e58909

**Comment by anmonteiro** [comment]
Same setup as https://github.com/mseri/doi2bib/pull/24, just changed the crossName to “riscv64”

**Comment by Kakadu** [comment]
> Same setup as [mseri/doi2bib#24](https://github.com/mseri/doi2bib/pull/24), just changed the crossName to “riscv64”, and got the package set from `pkgsCross.riscv64`

I did (I think) what you said, but compilation error about stdup is still here...

https://gist.github.com/Kakadu/2dfce256d756c537aab51eb9dfe3bf68

I also tried to copy-pate findlib's attribute from arm64-musl version to riscv64, but I get another error. Does overriding of OCAMLFIND_CONF is the source of my stdup issue?
```
       … while evaluating attribute 'OCAMLFIND_CONF' of derivation 'ocaml4.14.1-doi2bib-n-a-riscv64-unknown-linux-gnu'

         at /media/work/nix/store/kr39ms4h2kd91yxf84yjng5q20aqs2bl-source/flake.nix:51:15:

           50|             }).overrideAttrs (o: {
           51|               OCAMLFIND_CONF = pkgs'.ocamlPackages.findlib.makeFindlibConf native o;
             |               ^
           52|             });

       error: attribute 'makeFindlibConf' missing

       at /media/work/nix/store/kr39ms4h2kd91yxf84yjng5q20aqs2bl-source/flake.nix:51:32:

           50|             }).overrideAttrs (o: {
           51|               OCAMLFIND_CONF = pkgs'.ocamlPackages.findlib.makeFindlibConf native o;
             |                                ^
           52|             });
```

**Comment by anmonteiro** [comment]
you'll probably want to `nix flake update` to get the newest version of this repository.

**Comment by Kakadu** [comment]
Thanks! I managed to compile this!
