### ISSUE TITLE
Builds "succeed" despite build errors

### ISSUE THREAD

**Issue by wokalski** [nix-ocaml/nix-overlays#1699]
I was excited to try ocaml 5.3. I'm using core so there's plenty of JaneStreet packages that I'm relying on and long story short ppx_globalize build fails (as well as typerep) and probably a couple others.

I know it's not a problem with the overlays but the overlays suggest that everything builds :D with the build success thing

**Comment by anmonteiro** [comment]
indeed. we do this for pre-releases. check https://github.com/nix-ocaml/nix-overlays/blob/cd96184f5f1ae5ffaf9e002331dfa1de9ec4dbdb/.github/workflows/pipeline.yml#L36
