### ISSUE TITLE
libcurl.so: undefined reference to SSL_get0_group_name@OPENSSL_3.2.0

### ISSUE THREAD

**Issue by art-w** [nix-ocaml/nix-overlays#1816]
Hello! I'm not sure if this is the right place to report this, but the issue is very obscure as a nix newbie, so any help would be appreciated! I'm running into a linker error after updating the `flake.lock` of Cohttp: https://github.com/mirage/ocaml-cohttp/pull/1099 (see the failed Nix CI, note that it was working before)

```
libcurl.so: undefined reference to `SSL_get0_group_name@OPENSSL_3.2.0'
```

Would you have any suggestions on how to address this or who to ask for help? Thanks!

**Comment by anmonteiro** [comment]
fixed in #1824
