### ISSUE TITLE
Cannot coerce a set into a string

### ISSUE THREAD

**Issue by cdmistman** [nix-ocaml/nix-overlays#611]
I'm on nix v2.13.0

When attempting to use your overlay in my `shell.nix` a la:
```nix
let
  nixpkgs = <nixpkgs>;
  ocaml-overlay = builtins.fetchTarball
      https://github.com/nix-ocaml/nix-overlays/archive/master.tar.gz;
in with import nixpkgs {
  overlays = [
    (import "${ocaml-overlay}/overlay" { inherit nixpkgs; })
  ];
}; ...
```

I get the error `cannot coerce a set into a string` pointing to <https://github.com/nix-ocaml/nix-overlays/blob/1a1f0f82ea1d2fb37ab2e0f4a305f092f52f219a/ocaml/default.nix#L595>

**Comment by anmonteiro** [comment]
How about using `extraOverlays` like here? https://github.com/anmonteiro/piaf/blob/master/nix/ci/test.nix#L10-L16

**Comment by anmonteiro** [comment]
oh nevermind, that's not using `nixpkgs` upstream. I'll take a look at this soon

**Comment by anmonteiro** [comment]
I think what you want is `(import "${ocaml-overlay}/overlay" nixpkgs)`, not `{ inherit nixpkgs; }`

**Comment by cdmistman** [comment]
ah, yes - that seems to fix it, thank you! Perhaps the readme should be updated to reflect this? Or is `custom-nixpkgs` variable expected to represent something else? (I'm new to nix, this is my first `shell.nix` file :) )

**Comment by anmonteiro** [comment]
The readme does look wrong. Wanna send a PR since you got it working?

**Comment by cdmistman** [comment]
Can do, I also want to add `cohttp-eio` to the overlay so I'll submit that in a separate PR 😄

**Comment by anmonteiro** [comment]
there's https://github.com/nix-ocaml/nix-overlays/pull/534 but there's a few problems

**Comment by cdmistman** [comment]
i've got time today and my project using cohttp isn't urgent - what needs to be done to make `cohttp_async_websocket` compatible?
