### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by alyssais** [nix-ocaml/nix-overlays#704]
I don't see any license in this repo, which means that legally there's very little people can use this code for.  This would be a blocker for somebody other than the copyright holder [upstreaming the cross compilation support](#698).

I suggest copying the license structure of Nixpkgs, particularly the note about patches being licensed under the licenses of their respective upstreams, to allow for upstreaming.

**Comment by anmonteiro** [comment]
Thanks! This is a huge oversight indeed. I had thought about this a while ago and never did anything about it.


Do you have a link to the language nixpkgs uses for the patches? I found the `COPYING` file but it doesn't have that language.

**Comment by alyssais** [comment]
It's [here](https://github.com/nixos/nixpkgs#license), in the README.
