### ISSUE TITLE
Support for aarch64-darwin broken?

### ISSUE THREAD

**Issue by neshtea** [nix-ocaml/nix-overlays#832]
I have been using the `nix-ocaml/ocaml-overlays` for a while now.  Recently, I tried to update my flake-inputs and have been receiving a 

```
error: attribute 'aarch64-darwin' missing

       at /nix/store/5pn4hvrbh34ri3b60z7dqaszipbxc8v6-source/flake.nix:26:24:

           25|           inherit system;
           26|           overlays = [ inputs.ocaml-overlay.overlays.${system} ];
             |                        ^
           27|         };
```

The relevant parts of my `flake.nix` are:

```nix
{
  inputs = {
    ...
    ocaml-overlay = {
      url = "github:nix-ocaml/nix-overlays";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    ...
  };

  outputs = { self, nixpkgs, ... }@inputs:
    let
      supportedSystems = with inputs.flake-utils.lib.system; [ aarch64-darwin ];
    in inputs.flake-utils.lib.eachSystem supportedSystems (system:
      let
        overlays = [ inputs.ocaml-overlay.overlays.${system} ];
        pkgs = import nixpkgs {
          inherit system overlays;
        };
      in { ... });
}
```

Nothing else has changed and going back to my previous `flake.lock` has it working again. 

Has something happened to the `aarch64-darwin` support?  Or did the project's structure change and it is not reflected in the README?

**Comment by ulrikstrid** [comment]
I think it changed in this commit: [68b687f7e85889daae89915a984e97a5b375175b](https://github.com/nix-ocaml/nix-overlays/commit/68b687f7e85889daae89915a984e97a5b375175b#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0)

And I think you can just drop the `${system}` part of it since we're not doing any trickery anymore.

**Comment by neshtea** [comment]
If I take this literally, it should be something like this (which it obviously isn't 

```
        overlays = [ inputs.ocaml-overlay.overlays ];
        pkgs = import nixpkgs { inherit system overlays; };
```

Which results in

```
error: All overlays passed to nixpkgs must be functions.
```

**Comment by neshtea** [comment]
> shouldn't it be `inputs.ocaml-overlay.overlays.default`?

Exactly, my bad.  It workds now, thanks!
